#!/usr/bin/env python
"""Generate README and LaTeX language validation tables from template metadata."""

import argparse
import tomllib
from dataclasses import dataclass
from pathlib import Path

START_MARKER = "<!-- LANGUAGE TABLE START -->"
END_MARKER = "<!-- LANGUAGE TABLE END -->"


@dataclass(frozen=True)
class LanguageValidation:
    language: str
    model: str
    human: str
    error: str


def _completed_value(records: list[dict], key: str) -> str:
    values = [record[key] for record in records]
    return "; ".join(sorted(set(values))) if all(value != "none" for value in values) else ""


def collect_language_validation(templates_root: Path) -> list[LanguageValidation]:
    """Summarize each validation only when it covers every active template."""
    languages = []
    for lang_dir in sorted(path for path in templates_root.iterdir() if path.is_dir()):
        if (lang_dir / "ignore").exists():
            continue
        records = []
        for path in sorted((lang_dir / "symbolic").glob("*.toml")):
            with path.open("rb") as file:
                record = tomllib.load(file)
            if not record.get("ignore"):
                records.append(record)
        if not records:
            continue
        for record in records:
            assert not {"creation", "model", "computationally-validated"}.intersection(record), (
                f"{lang_dir.name}: obsolete metadata"
            )
            assert record["language"] == lang_dir.name, f"{lang_dir.name}: incorrect language"
            if lang_dir.name not in {"eng", "eng_metric"}:
                assert record["initial_translation_model"] != "none", f"{lang_dir.name}: missing translation model"
                assert record["source-language"] != "none", f"{lang_dir.name}: missing source language"
        human_values = [record["human-validated"] for record in records]
        human = _completed_value(records, "human-validated")
        if any("in progress" in value.lower() for value in human_values) or (
            not human and any(value != "none" for value in human_values)
        ):
            human = "In progress"
        languages.append(
            LanguageValidation(
                language=lang_dir.name,
                model=_completed_value(records, "initial_translation_model"),
                human=human,
                error=_completed_value(records, "error-analysis"),
            )
        )
    return languages


def _markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", "<br>")


def _included_languages(languages: list[LanguageValidation]) -> list[LanguageValidation]:
    return [lang for lang in languages if lang.language != "eng_metric" and (lang.human or lang.language == "eng")]


def render_language_tables(languages: list[LanguageValidation]) -> str:
    lines = [
        "The following languages are human validated or in progress, alongside the English originals. Computational validation is enforced by CI.",
        "",
        "| Language | Computationally validated | Human validated | Error analysis |",
        "| --- | --- | --- | --- |",
    ]
    for lang in _included_languages(languages):
        error = "✓" if lang.error else ""
        lines.append(f"| `{lang.language}` | ✓ | {_markdown_cell(lang.human)} | {error} |")
    return "\n".join(lines)


def _latex_cell(value: str) -> str:
    escapes = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "\n": " ",
    }
    return "".join(escapes.get(char, char) for char in value)


def render_latex_table(languages: list[LanguageValidation]) -> str:
    """One row per language, with single-line cells; requires amssymb."""
    lines = [
        "% Generated by src/scripts/update_readme_table.py; do not edit.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llccl}",
        r"\hline",
        r"Language & Human review & Comp. & Error analysis & Initial translation model \\",
        r"\hline",
    ]
    for lang in _included_languages(languages):
        values = [
            _latex_cell(lang.language),
            _latex_cell(lang.human.removeprefix("by ")),
            r"$\checkmark$",
            r"$\checkmark$" if lang.error else "",
            _latex_cell(lang.model),
        ]
        lines.append(" & ".join(values) + r" \\")
    lines.extend(
        [
            r"\hline",
            r"\end{tabular}",
            r"\caption{Human-validated languages and reviews in progress, alongside the English originals. Computational validation is enforced by CI. Error analysis is marked only when complete for all active templates.}",
            r"\label{tab:language-validation}",
            r"\end{table*}",
        ]
    )
    return "\n".join(lines) + "\n"


def update_readme(readme: Path, table_content: str) -> None:
    text = readme.read_text(encoding="utf-8")
    assert text.count(START_MARKER) == text.count(END_MARKER) == 1, "README table markers must occur once"
    before, remainder = text.split(START_MARKER)
    _, after = remainder.split(END_MARKER)
    readme.write_text(f"{before}{START_MARKER}\n{table_content}\n{END_MARKER}{after}", encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    parser.add_argument("--templates-root", type=Path, default=Path("src/multilingual_gsm_symbolic/data/templates"))
    parser.add_argument("--latex", type=Path, default=Path("docs/language_validation.tex"))
    args = parser.parse_args()
    languages = collect_language_validation(args.templates_root)
    update_readme(args.readme, render_language_tables(languages))
    args.latex.parent.mkdir(parents=True, exist_ok=True)
    args.latex.write_text(render_latex_table(languages), encoding="utf-8", newline="\n")
    print(f"Updated {args.readme} and {args.latex} for {len(languages)} languages")


if __name__ == "__main__":
    main()
